#!/usr/bin/env bash
# One-command bootstrap for Codex on a new Mac after this repo is cloned.
#
# Usage:
#   scripts/codex-bootstrap.sh /path/to/insurance-agent-data-....tar.gz
#   DATA_PACKAGE_URL="https://..." scripts/codex-bootstrap.sh
#
# This script assumes Docker Desktop is already installed and running. macOS
# requires user/admin approval for the first Docker Desktop install.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PACKAGE_INPUT="${1:-${DATA_PACKAGE_URL:-}}"
START_TUNNEL="${START_TUNNEL:-1}"
APP_IMAGE="${APP_IMAGE:-insurance-agent-web:local}"
APP_PORT="${APP_PORT:-3000}"
DB_PORT="${DB_PORT:-5433}"

cd "$ROOT_DIR"

need_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "Missing required command: $1" >&2
    exit 1
  fi
}

rand_hex() {
  openssl rand -hex "$1"
}

compose() {
  docker compose --env-file .env -f docker-compose.prod.yml "$@"
}

wait_for_db() {
  echo "[bootstrap] waiting for Postgres"
  for _ in $(seq 1 60); do
    if compose exec -T db pg_isready -U admin -d insurance >/dev/null 2>&1; then
      return 0
    fi
    sleep 2
  done
  echo "Postgres did not become ready in time." >&2
  exit 1
}

latest_file() {
  local pattern="$1"
  find . -path "$pattern" -type f 2>/dev/null | sort | tail -1
}

download_or_extract_package() {
  mkdir -p deployment-data

  if [[ -z "$PACKAGE_INPUT" ]]; then
    PACKAGE_INPUT="$(find deployment-data -maxdepth 1 -type f -name 'insurance-agent-data-*.tar.gz' | sort | tail -1 || true)"
  fi

  if [[ -z "$PACKAGE_INPUT" ]]; then
    echo "[bootstrap] no deployment data package provided; continuing without restore"
    return 0
  fi

  local package_path="$PACKAGE_INPUT"
  if [[ "$PACKAGE_INPUT" =~ ^https?:// ]]; then
    package_path="deployment-data/$(basename "${PACKAGE_INPUT%%\?*}")"
    echo "[bootstrap] downloading data package"
    curl -L "$PACKAGE_INPUT" -o "$package_path"
  fi

  if [[ ! -f "$package_path" ]]; then
    echo "Data package not found: $package_path" >&2
    exit 1
  fi

  echo "[bootstrap] extracting data package: $package_path"
  tar -xzf "$package_path"
}

create_env_if_missing() {
  if [[ -f .env ]]; then
    echo "[bootstrap] using existing .env"
    return 0
  fi

  echo "[bootstrap] creating .env"

  local db_password jwt_secret vapid_json vapid_public vapid_private anthropic tunnel_domain tunnel_token
  db_password="$(rand_hex 24)"
  jwt_secret="$(rand_hex 32)"
  anthropic="${ANTHROPIC_API_KEY:-sk-ant-replace-me}"
  tunnel_domain="${TUNNEL_DOMAIN:-localhost:$APP_PORT}"
  tunnel_token="${CLOUDFLARE_TUNNEL_TOKEN:-}"

  vapid_json="$(docker run --rm node:20-alpine sh -c "npx -y web-push generate-vapid-keys --json")"
  vapid_public="$(node -e "const data=JSON.parse(process.argv[1]); console.log(data.publicKey)" "$vapid_json")"
  vapid_private="$(node -e "const data=JSON.parse(process.argv[1]); console.log(data.privateKey)" "$vapid_json")"

  cat > .env <<EOF
# Generated by scripts/codex-bootstrap.sh. Do not commit.
APP_IMAGE=$APP_IMAGE
DB_PASSWORD=$db_password
JWT_SECRET=$jwt_secret
ANTHROPIC_API_KEY=$anthropic

CLOUDFLARE_TUNNEL_TOKEN=$tunnel_token
TUNNEL_DOMAIN=$tunnel_domain
APP_PORT=$APP_PORT
DB_PORT=$DB_PORT

OLLAMA_URL=http://host.docker.internal:11434
OLLAMA_MODEL=qwen2.5:7b
OLLAMA_VISION_MODEL=qwen2.5vl:7b

WHISPER_URL=http://host.docker.internal:9000/inference
TRANSCRIBE_MAX_BYTES=26214400

GHCR_USER=${GHCR_USER:-}
GHCR_READ_TOKEN=${GHCR_READ_TOKEN:-}
WATCHTOWER_POLL_INTERVAL=3600

NEXT_PUBLIC_VAPID_PUBLIC_KEY=$vapid_public
VAPID_PRIVATE_KEY=$vapid_private
VAPID_SUBJECT=mailto:admin@team.local

BACKUP_HOST_DIR=./backups
BACKUP_RETENTION_DAYS=30
BACKUP_NOTIFY_URL=
TZ=Asia/Hong_Kong

SENTRY_DSN=
NEXT_PUBLIC_SENTRY_DSN=
EOF

  chmod 600 .env
}

restore_database_if_available() {
  local db_backup docs_backup
  db_backup="$(latest_file './backups/db-*.sql.gz')"
  docs_backup="$(latest_file './backups/docs-*.tar.gz')"

  if [[ -z "$db_backup" ]]; then
    echo "[bootstrap] no db backup found; leaving schema-only database"
    return 0
  fi

  echo "[bootstrap] restoring database: $db_backup"
  compose exec -T db psql -U admin -d insurance -c "DROP SCHEMA public CASCADE; CREATE SCHEMA public;"
  gunzip -c "$db_backup" | compose exec -T db psql -U admin -d insurance

  if [[ -n "$docs_backup" ]]; then
    echo "[bootstrap] restoring uploaded documents: $docs_backup"
    docker run --rm \
      -v insurance-agent-web_documents:/storage \
      -v "$ROOT_DIR/backups:/backups" \
      alpine sh -c "rm -rf /storage/documents && tar -xzf /backups/$(basename "$docs_backup") -C /storage"
  fi
}

mark_migrations_if_needed() {
  compose exec -T db psql -U admin -d insurance <<'SQL'
CREATE TABLE IF NOT EXISTS public.pgmigrations (
  id SERIAL PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  run_on TIMESTAMP NOT NULL
);
INSERT INTO public.pgmigrations (name, run_on)
SELECT name, NOW()
FROM (
  VALUES
    ('1715040001000_baseline-marker'),
    ('1715040002000_soft-delete'),
    ('1715040003000_documents'),
    ('1715040004000_push-subscriptions'),
    ('1715040005000_pgcrypto'),
    ('1715040006000_client-nationality-preferences'),
    ('1715040007000_security-audit'),
    ('1715040008000_normalize-policy-types'),
    ('1715040009000_login-attempts')
) AS wanted(name)
WHERE NOT EXISTS (
  SELECT 1 FROM public.pgmigrations existing WHERE existing.name = wanted.name
);
SQL
}

build_app_image() {
  if [[ "$APP_IMAGE" == "insurance-agent-web:local" ]]; then
    echo "[bootstrap] building local app image"
    docker build -t "$APP_IMAGE" .
  else
    echo "[bootstrap] pulling app image: $APP_IMAGE"
    docker pull "$APP_IMAGE"
  fi
}

start_trycloudflare() {
  if [[ "$START_TUNNEL" != "1" ]]; then
    return 0
  fi

  echo "[bootstrap] starting temporary TryCloudflare tunnel"
  docker rm -f insurance-agent-web-trycloudflare >/dev/null 2>&1 || true
  docker run -d --name insurance-agent-web-trycloudflare \
    cloudflare/cloudflared:latest tunnel --url "http://host.docker.internal:$APP_PORT" >/dev/null

  sleep 4
  docker logs insurance-agent-web-trycloudflare 2>&1 | \
    grep -Eo 'https://[-a-zA-Z0-9]+\.trycloudflare\.com' | tail -1 || true
}

verify_install() {
  echo "[bootstrap] verification"
  compose ps
  curl -fsSI "http://localhost:$APP_PORT" >/dev/null

  compose exec -T db psql -U admin -d insurance \
    -c "SELECT COUNT(*) AS active_knowledge_rows FROM company_knowledge WHERE is_active = TRUE;"

  if curl -fsS http://host.docker.internal:11434/api/tags >/dev/null 2>&1; then
    echo "[bootstrap] Ollama reachable from Docker host bridge"
  else
    echo "[bootstrap] Ollama not reachable yet; install/start Ollama if local model features are needed"
  fi

  if curl -fsS http://host.docker.internal:9000/inference >/dev/null 2>&1; then
    echo "[bootstrap] Whisper endpoint reachable"
  else
    echo "[bootstrap] Whisper endpoint not reachable yet; start whisper-server for voice input"
  fi
}

main() {
  need_cmd docker
  need_cmd openssl
  need_cmd curl
  need_cmd tar
  need_cmd gunzip
  need_cmd node

  docker info >/dev/null

  download_or_extract_package
  create_env_if_missing

  build_app_image
  compose up -d db
  wait_for_db
  restore_database_if_available
  mark_migrations_if_needed
  compose up -d --build backup
  compose up -d migrate app worker

  local tunnel_url
  tunnel_url="$(start_trycloudflare)"
  verify_install

  echo
  echo "[bootstrap] done"
  echo "Local URL: http://localhost:$APP_PORT"
  if [[ -n "$tunnel_url" ]]; then
    echo "TryCloudflare URL: $tunnel_url"
  fi
  echo "Default fresh login: admin@team.local / Admin@1234"
}

main "$@"
